"""Legacy invocation-evidence compatibility names for approval-ledger operations."""

from orchestration.lib.ledger import (
    AbsentApprovalError,
    CeremonyIOError,
    EventValidationError,
    ExpiredApprovalError,
    FinishAttemptError,
    FutureIssuedApprovalError,
    InvocationBinding,
    LedgerError,
    LedgerIOError,
    MalformedLedgerEntryError,
    NaiveDatetimeError,
    ReplayedInvocationError,
    StaleInvocationDigestError,
    StalePromptDigestError,
    StaleRegistryDigestError,
    StaleScopeDigestError,
    StaleTaskDigestError,
    WrongAliasError,
    append_event,
    approve_interactively,
    consume_approval_and_start,
    finish_attempt,
    make_binding,
    validate_event,
)


__all__ = (
    "AbsentApprovalError",
    "CeremonyIOError",
    "EventValidationError",
    "ExpiredApprovalError",
    "FinishAttemptError",
    "FutureIssuedApprovalError",
    "InvocationBinding",
    "LedgerError",
    "LedgerIOError",
    "MalformedLedgerEntryError",
    "NaiveDatetimeError",
    "ReplayedInvocationError",
    "StaleInvocationDigestError",
    "StalePromptDigestError",
    "StaleRegistryDigestError",
    "StaleScopeDigestError",
    "StaleTaskDigestError",
    "WrongAliasError",
    "append_event",
    "approve_interactively",
    "consume_approval_and_start",
    "finish_attempt",
    "make_binding",
    "validate_event",
)
